services:
  - type: web
    name: music-backend
    runtime: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y ffmpeg
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: FFMPEG_PATH
        value: /usr/bin/ffmpeg
    plan: free