services:
  - type: web
    name: music-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      sudo apt-get update && sudo apt-get install -y ffmpeg
    startCommand: gunicorn server:app
    envVars:
      - key: FFMPEG_PATH
        value: /usr/bin/ffmpeg
    plan: free  # Remove for paid plans